/** Server error text (English — the API contract does not change) → key in the "apiErrors" messages namespace. */
export const apiErrorKeyByMessage: Readonly<Record<string, string>> = {
  "A status or condition target is required": "stateTargetRequired",
  "Active checkout not found": "activeCheckoutNotFound",
  "Actual sale value is required": "saleValueRequired",
  "Archive path must stay inside the upload directory": "storagePathOutsideUploads",
  "Asset already has an active checkout": "assetActiveCheckoutExists",
  "Asset data changed after this audit finding was reported": "findingAssetChanged",
  "Asset has no current custodian to backfill": "assetNoCustodianToBackfill",
  "Asset label height must be between 10 and 100 mm": "labelHeightRange",
  "Asset label layout is not supported": "labelLayoutUnsupported",
  "Asset label QR size must be between 20 and 90 px": "labelQrSizeRange",
  "Asset label spacing must be between 0 and 10 mm": "labelSpacingRange",
  "Asset label template uses unsupported tokens": "labelTemplateTokens",
  "Asset label toggle values must be true or false": "labelToggleInvalid",
  "Asset label width must be between 30 and 120 mm": "labelWidthRange",
  "Asset not found": "assetNotFound",
  "Asset not found or inactive": "assetNotFoundOrInactive",
  "Asset status changed while creating the disposal request": "assetStatusChangedDuringDisposal",
  "Asset status changed while this request was being saved. Reload the asset and try again.": "assetChangedDuringOperation",
  "Asset status does not allow a new disposal request": "disposalAssetIneligible",
  "Asset status does not allow checkout": "statusBlocksCheckout",
  "Asset status does not allow transfer": "statusBlocksTransfer",
  "Asset status not found": "assetStatusNotFound",
  "Asset tag batch size must be between 1 and 100": "assetTagBatchSize",
  "Asset tag format template must include {running} and only use supported tokens": "assetTagTemplateInvalid",
  "ASSET_ACTIVE_CHECKOUT_EXISTS": "assetActiveCheckoutExists",
  "ASSET_CHANGED_DURING_OPERATION": "assetChangedDuringOperation",
  "ASSET_STATE_REVIEW_MASTER_NOT_FOUND": "stateReviewMasterNotFound",
  "ASSET_STATE_REVIEW_NOT_FOUND": "stateReviewNotFound",
  "ASSET_STATE_REVIEW_NOT_PENDING": "stateReviewNotPending",
  "ASSET_STATE_REVIEW_REASON_REQUIRED": "stateReviewReasonRequired",
  "ASSET_STATE_REVIEW_STALE": "stateReviewStale",
  "ASSET_STATE_REVIEW_TARGET_NOT_ALLOWED": "stateReviewTargetNotAllowed",
  "At least one bulk update field is required": "bulkUpdateFieldRequired",
  "At least one integration scope is required": "integrationScopeRequired",
  "At least one transfer destination is required": "transferDestinationRequired",
  "Attachment file not found": "attachmentFileNotFound",
  "Attachment is not an image": "attachmentNotImage",
  "Attachment not found": "attachmentNotFound",
  "Audit finding has already been reviewed": "findingAlreadyDecided",
  "Audit finding must be reviewed by a different user than the reporter": "findingReviewerIsReporter",
  "Audit finding not found": "findingNotFound",
  "Audit item not found": "auditItemNotFound",
  "Audit round is cancelled": "auditRoundCancelled",
  "Audit round is closed": "auditRoundClosed",
  "Audit round must be closed by a different approver than the creator": "auditRoundCloserIsCreator",
  "Audit round not found": "auditRoundNotFound",
  "Audit round still has pending checklist items": "auditRoundHasPendingItems",
  "Batch create requires at least 2 rows": "batchCreateMinRows",
  "Batch create supports up to 100 rows": "batchCreateMaxRows",
  "Branch not found": "branchNotFound",
  "Brand not found": "brandNotFound",
  "Cannot generate a unique operation document number": "documentNumberFailed",
  "Cannot generate a unique transfer document number": "documentNumberFailed",
  "Cannot remove or deactivate the last active system administrator": "lastSystemAdmin",
  "Category not found": "categoryNotFound",
  "Company not found": "companyNotFound",
  "Component asset cannot be the same as parent asset": "componentSameAsParent",
  "Component asset not found": "componentNotFound",
  "Component confirmation reason is required": "componentConfirmReasonRequired",
  "Component confirmation transaction retry failed": "componentConfirmRetryFailed",
  "Component is no longer installed under the selected parent asset": "componentNotUnderParent",
  "Component is not included in this audit round": "componentNotInRound",
  "Component parent is not included in this audit round": "componentParentNotInRound",
  "Custodian is required": "custodianRequired",
  "Custodian not found": "custodianNotFound",
  "Default asset label tape size must be 12, 18, 24, or custom": "labelTapeSizeInvalid",
  "Department is required": "departmentRequired",
  "Department not found": "departmentNotFound",
  "Depreciation policy must be valid JSON with useful life 1-600 months and residual rate 0-0.9": "depreciationPolicyInvalid",
  "Disposal approval must keep the asset status Pending Disposal": "disposalApprovalKeepsPending",
  "Disposal approvers must be linked to an employee record while segregation of duties is required": "disposalApproverNeedsEmployee",
  "Disposal batch asset IDs must be unique": "disposalBatchDuplicateAssets",
  "Disposal batch database migration is required": "disposalBatchMigrationRequired",
  "Disposal batch not found": "disposalBatchNotFound",
  "Disposal batch requires a supported disposal type": "disposalBatchTypeRequired",
  "Disposal batch requires at least 2 asset IDs": "disposalBatchMinAssets",
  "Disposal batch supports up to 100 asset IDs": "disposalBatchMaxAssets",
  "Disposal execution can only set asset status to Disposed or Retired": "disposalExecutionStatusInvalid",
  "Disposal reason must contain at least 12 characters": "disposalReasonTooShort",
  "Disposal rejection can only return the asset status to Ready": "disposalRejectReturnsReady",
  "Disposal request IDs must be unique": "disposalDuplicateRequests",
  "Disposal request is already reviewed": "disposalAlreadyDecided",
  "Disposal request not found": "disposalRequestNotFound",
  "DISPOSAL_APPROVAL_FAILED": "disposalApprovalFailed",
  "DISPOSAL_ASSET_INELIGIBLE": "disposalAssetIneligible",
  "DISPOSAL_BATCH_SCHEMA_CHECK_FAILED": "disposalBatchSchemaCheckFailed",
  "DISPOSAL_BULK_EXECUTION_FAILED": "disposalBulkExecutionFailed",
  "DISPOSAL_CONCURRENT_UPDATE": "disposalConcurrentUpdate",
  "DISPOSAL_EMPLOYEE_NOT_FOUND": "disposalEmployeeNotFound",
  "DISPOSAL_EVIDENCE_EXCEPTION_REASON_REQUIRED": "disposalEvidenceExceptionReasonRequired",
  "DISPOSAL_EXECUTION_FAILED": "disposalExecutionFailed",
  "DISPOSAL_FORBIDDEN": "forbidden",
  "DISPOSAL_INVALID_STAGE": "disposalAlreadyDecided",
  "DISPOSAL_INVALID_STATUS_TARGET": "disposalInvalidStatusTarget",
  "DISPOSAL_REQUEST_NOT_FOUND": "disposalRequestNotFound",
  "DISPOSAL_SOD_CONFLICT": "disposalSameRequesterApprover",
  "DISPOSAL_STATUS_NOT_FOUND": "disposalNextStatusNotFound",
  "Disposed or retired assets cannot be moved.": "disposedAssetCannotMove",
  "Employee already has a user account": "employeeHasUser",
  "Employee cannot be their own manager": "employeeOwnManager",
  "Employee not found": "employeeNotFound",
  "End date must be after start date": "endBeforeStart",
  "Enter the bind password to test a different LDAP server or bind account": "ldapBindPasswordNeeded",
  "Evidence attachment is invalid for this asset": "evidenceAttachmentInvalid",
  "Evidence attachment is required for changed out-of-scope actual fields": "evidenceRequiredOutOfScope",
  "Execution or incident detail is required": "executionDetailRequired",
  "File content does not match the uploaded file type": "fileContentMismatch",
  "File extension is not allowed": "fileExtensionNotAllowed",
  "File is empty": "fileEmpty",
  "File is required": "fileRequired",
  "File is still attached to an active record": "fileStillAttached",
  "File size exceeds 10 MB": "fileTooLarge",
  "File type is not allowed": "fileTypeNotAllowed",
  "Finish or cancel the unfinished repair record before creating a legacy return": "legacyReturnRepairOpen",
  "Forbidden: cannot modify a user who has access you do not hold": "userHasMoreAccess",
  "Forbidden: insufficient permissions": "forbidden",
  "Forbidden: only system_admin can apply LDAP sync": "ldapSyncAdminOnly",
  "Forbidden: only system_admin can grant the system_admin role": "grantSystemAdminForbidden",
  "Forbidden: only system_admin can test LDAP connections": "ldapTestAdminOnly",
  "HANDOVER_MODE_REQUIRED": "handoverModeRequired",
  "HANDOVER_PERMANENT_CUSTODIAN_REQUIRED": "handoverPermanentCustodianRequired",
  "HANDOVER_PERMANENT_DUE_DATE_NOT_ALLOWED": "handoverPermanentNoDueDate",
  "HANDOVER_PERMANENT_USER_ONLY": "handoverPermanentUserOnly",
  "HANDOVER_RETURN_BEFORE_CHECKOUT": "handoverReturnBeforeCheckout",
  "HANDOVER_TEMPORARY_DUE_DATE_REQUIRED": "handoverTemporaryDueDateRequired",
  "Image could not be processed": "imageProcessFailed",
  "Installed component not found": "installedComponentNotFound",
  "Installing this component would create a parent/child cycle": "componentCycle",
  "Integration client not found": "integrationClientNotFound",
  "Integration scopes JSON is malformed": "integrationScopesInvalid",
  "Integration scopes JSON must be a string": "integrationScopesInvalid",
  "Integration scopes must be an array": "integrationScopesInvalid",
  "Integration scopes must contain only non-blank strings": "integrationScopesInvalid",
  "INTEGRATION_ASSET_NOT_FOUND": "assetNotFound",
  "INTEGRATION_ERROR": "integrationError",
  "INTEGRATION_FORBIDDEN": "forbidden",
  "INTEGRATION_UNAUTHORIZED": "unauthorized",
  "INTEGRATION_UPDATED_SINCE_REQUIRED": "integrationUpdatedSinceRequired",
  "Invalid asset condition for checkout": "invalidCheckoutCondition",
  "Invalid asset tag master data": "invalidAssetTagMasterData",
  "Invalid asset transaction snapshot": "invalidTransactionSnapshot",
  "Invalid asset transaction snapshot input": "invalidTransactionSnapshot",
  "Invalid assignee": "invalidAssignee",
  "Invalid attachment path": "invalidAttachmentPath",
  "Invalid component transaction snapshot": "invalidTransactionSnapshot",
  "Invalid JSON body": "invalidRequest",
  "Invalid maintenance option type": "invalidMaintenanceOption",
  "Invalid notification action": "invalidNotificationAction",
  "Invalid permission selection": "invalidPermissionSelection",
  "Invalid return condition for check-in": "invalidReturnCondition",
  "Invalid return status for check-in": "invalidReturnStatus",
  "Invalid role selection": "invalidRoleSelection",
  "Invalid since": "invalidRequest",
  "Invalid supplier data": "invalidSupplierData",
  "Invalid transaction snapshot date": "invalidTransactionSnapshot",
  "LDAP is disabled": "ldapDisabled",
  "LDAP sync base DN is required": "ldapSyncBaseDnRequired",
  "LDAP sync is disabled": "ldapSyncDisabled",
  "LDAP sync is not enabled": "ldapSyncDisabled",
  "LDAP URL, Bind DN, and Bind Password are required": "ldapSettingsRequired",
  "Location cannot be its own parent": "locationOwnParent",
  "Location hierarchy cannot contain a cycle": "locationCycle",
  "Location is required": "locationRequired",
  "Location not found": "locationNotFound",
  "Maintenance plan asset not found or inactive": "maintenancePlanAssetNotFound",
  "Maintenance plan not found": "maintenancePlanNotFound",
  "Maintenance ticket not found": "maintenanceTicketNotFound",
  "MAINTENANCE_ASSET_INELIGIBLE": "maintenanceAssetIneligible",
  "MAINTENANCE_ASSET_ON_LOAN": "maintenanceAssetOnLoan",
  "MAINTENANCE_ASSET_WRITTEN_OFF": "maintenanceAssetWrittenOff",
  "MAINTENANCE_CONFLICT": "maintenanceConflict",
  "MAINTENANCE_INVALID_TRANSITION": "maintenanceRecordFinished",
  "MAINTENANCE_OPEN_RECORD_EXISTS": "maintenanceOpenRecordExists",
  "MAINTENANCE_PLAN_INVALID_TRANSITION": "maintenancePlanInactive",
  "MAINTENANCE_REPORTER_REQUIRED": "maintenanceReporterRequired",
  "Missing generated asset tag": "assetTagMissing",
  "Missing SQL Server connection settings in environment variables": "dbSettingsMissing",
  "Model not found": "modelNotFound",
  "Model photo must be an image": "modelPhotoNotImage",
  "Next asset status not found": "disposalNextStatusNotFound",
  "No assets found in audit scope": "auditScopeEmpty",
  "No assets selected": "noAssetsSelected",
  "Notification rule days must be an integer between 0 and 365": "notificationDaysRange",
  "One or more assets were not found": "someAssetsNotFound",
  "Only pending audit items can be marked as not found": "auditItemNotPending",
  "Operation document running digits must be between 1 and 12": "documentRunningDigitsRange",
  "Operation document template must include {running} and only use supported tokens": "documentTemplateInvalid",
  "Parent asset is required": "parentAssetRequired",
  "Parent asset not found": "parentAssetNotFound",
  "parentAssetId is required": "parentAssetRequired",
  "Password is required": "passwordRequired",
  "Pending Disposal asset status is not configured": "pendingDisposalStatusMissing",
  "Please attach closure evidence before closing this finding": "findingClosureEvidenceRequired",
  "PM vendor not found or inactive": "pmVendorNotFound",
  "Protected lifecycle statuses must be changed through the proper workflow or status correction": "protectedStatusChange",
  "Public QR base URL must be a valid http or https URL": "publicQrUrlInvalid",
  "Purchase document already exists": "purchaseDocumentExists",
  "Reference document number is required": "referenceDocumentRequired",
  "Rejection reason is required": "rejectionReasonRequired",
  "Repair record not found": "repairRecordNotFound",
  "Reporter not found or inactive": "reporterNotFound",
  "Requester and assigned approver must be different": "disposalSameRequesterApprover",
  "Requester or approver is inactive or missing": "disposalEmployeeNotFound",
  "Retention policy days must be an integer between 1 and 3650": "retentionDaysRange",
  "Role name already exists": "roleNameExists",
  "Role not found": "roleNotFound",
  "Scheduled LDAP sync requires scheduler token": "ldapSchedulerTokenRequired",
  "Scheduler mode must be preview, manual, or scheduled": "schedulerModeInvalid",
  "Scheduler schedule must be a supported five-field cron expression": "schedulerCronInvalid",
  "Select who is recording this repair": "maintenanceReporterRequired",
  "Serial Number already exists": "serialNumberExists",
  "Some assets already have active checkouts": "someAssetsOnCheckout",
  "Some assets cannot be updated in bulk. Use the transfer, return, or disposal workflow for them.": "someAssetsNeedWorkflow",
  "Some assets were not found": "someAssetsNotFound",
  "Source path must stay inside the upload directory": "storagePathOutsideUploads",
  "Status correction can only return protected lifecycle statuses to Ready": "statusCorrectionReadyOnly",
  "Storage archive target must be a file": "storageTargetNotFile",
  "Storage path cannot contain traversal": "storagePathInvalid",
  "Storage path cannot point inside the archive": "storagePathInArchive",
  "Storage path must be relative": "storagePathInvalid",
  "Storage relative path is required": "storagePathRequired",
  "Supplier code already exists": "supplierCodeExists",
  "Supplier not found": "supplierNotFound",
  "System administrator permissions are protected": "systemAdminPermissionsProtected",
  "The approver cannot execute the disposal request": "disposalApproverCannotExecute",
  "The asset must remain Pending Disposal before approval": "disposalAssetMustBePending",
  "The asset or record changed just now; reload and try again": "maintenanceConflict",
  "The PM plan is not active for this asset": "maintenancePlanInactive",
  "The request creator cannot approve their own disposal request": "disposalCreatorCannotApprove",
  "The requester cannot approve their own disposal request": "disposalRequesterCannotApprove",
  "This approval has no recorded approver, so segregation of duties cannot be verified before execution": "disposalApproverUnknown",
  "This asset status does not require controlled correction": "statusCorrectionNotNeeded",
  "This parent asset already has a component in the same slot": "componentSlotTaken",
  "This record is already finished or cancelled": "maintenanceRecordFinished",
  "Too many component transaction snapshots": "tooManyComponentSnapshots",
  "TRANSACTION_CANCELLATION_BLOCKED": "transactionCancellationBlocked",
  "TRANSACTION_NOT_FOUND": "transactionNotFound",
  "TRANSACTION_SNAPSHOT_UNSUPPORTED": "transactionSnapshotUnsupported",
  "TRANSACTION_STALE": "transactionStale",
  "Unauthorized": "unauthorized",
  "Unexpected error": "unexpected",
  "Unsupported audit round action": "unsupportedAuditRoundAction",
  "Uploaded file failed malware scan": "fileMalwareDetected",
  "Used license seats cannot exceed total seats": "licenseSeatsExceeded",
  "User not found": "userNotFound",
  "Username already exists": "usernameExists",
  "Vendor not found or inactive": "vendorNotFound",
  "Workflow approval minimum approvers must be an integer between 1 and 5": "approvalMinApproversRange",
  "Workflow approval SLA days must be an integer between 1 and 90": "approvalSlaDaysRange",
  "Workflow approval toggle values must be true or false": "approvalToggleInvalid",
}

export type ApiErrorDescription = { message: string; detail: string | null }

const thaiText = /[\u0E00-\u0E7F]/

export function getApiErrorKey(raw: string): string | null {
  return apiErrorKeyByMessage[raw.trim()] ?? null
}

export function describeApiError(
  raw: string | null | undefined,
  labels: { lookup: (key: string) => string; unknown: string; empty: string },
): ApiErrorDescription {
  const text = raw?.trim() ?? ""
  if (!text) return { message: labels.empty, detail: null }
  if (thaiText.test(text)) return { message: text, detail: null }
  const key = getApiErrorKey(text)
  const message = key ? labels.lookup(key) : labels.unknown
  return { message, detail: message === text ? null : text }
}
