import { NextResponse } from "next/server"

export const disposalApiErrorCodes = [
  "DISPOSAL_ASSET_NOT_FOUND",
  "DISPOSAL_EMPLOYEE_NOT_FOUND",
  "DISPOSAL_OPEN_REQUEST",
  "DISPOSAL_ASSET_INELIGIBLE",
  "DISPOSAL_ASSET_BLOCKED",
  "DISPOSAL_PENDING_STATUS_MISSING",
  "DISPOSAL_REQUEST_NOT_FOUND",
  "DISPOSAL_INVALID_STAGE",
  "DISPOSAL_SOD_CONFLICT",
  "DISPOSAL_CONCURRENT_UPDATE",
  "DISPOSAL_APPROVAL_FAILED",
  "DISPOSAL_STATUS_NOT_FOUND",
  "DISPOSAL_INVALID_STATUS_TARGET",
  "DISPOSAL_EXECUTION_FAILED",
  "DISPOSAL_EVIDENCE_REQUIRED",
  "DISPOSAL_EVIDENCE_EXCEPTION_FORBIDDEN",
  "DISPOSAL_EVIDENCE_EXCEPTION_REASON_REQUIRED",
  "DISPOSAL_EVIDENCE_EXCEPTION_ACK_REQUIRED",
  "DISPOSAL_EVIDENCE_EXCEPTION_NOT_APPLICABLE",
] as const

export type DisposalApiErrorCode = (typeof disposalApiErrorCodes)[number]

export function disposalApiError(code: DisposalApiErrorCode, error: string, status = 400) {
  return NextResponse.json({ code, error }, { status })
}
