// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function env(name: string) {
  return process.env[name]?.trim().replace(/^"|"$/g, "");
}

function databaseFromUrl() {
  const database = env("DATABASE_URL")?.match(/(?:^|;)database=([^;]+)/i)?.[1];
  return database ? decodeURIComponent(database) : undefined;
}

function sqlServerUrl() {
  const server = env("DB_SERVER");
  const instanceName = env("DB_INSTANCE");
  const port = env("DB_PORT");
  const database = databaseFromUrl();
  const user = env("DB_USER");
  const password = env("DB_PASSWORD");

  if (!server || !database || !user || !password) {
    return process.env["DATABASE_URL"];
  }

  const host = instanceName ? `${server}\\${instanceName}` : `${server}:${port ?? "1433"}`;

  return `sqlserver://${host};database=${database};user=${user};password=${password};encrypt=true;trustServerCertificate=true`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: sqlServerUrl(),
  },
});
